### ISSUE TITLE
TypeError: this.bjsAMMO.btSoftBodyRigidBodyCollisionConfiguration is not a constructor

### ISSUE THREAD

**Issue by visuallization** [RaananW/babylonjs-webpack-es6#1]
Hey there!

First of all thank you for your Babylon starter template, really appreciate that.

Everything works nice but if I got to: `http://localhost:8080/?scene=physicsWithAmmo` it throws an error:

![image](https://user-images.githubusercontent.com/6199277/86367771-a812ea80-bc7c-11ea-8221-e8019785288d.png)

It seems to have problems initialising ammo but I still don't know why.
Do you have any ideas?

Working on chrome on a mac.

Cheers,
Florentin

**Comment by RaananW** [comment]
Congrats! first issue :-)

I am pretty sure I actually solved this, but it seems like a newer version of Ammo introduced it back.

I will check this and update here!

**Comment by RaananW** [comment]
Ok! Just pushed a fix to master. I was incorrectly handling the ammo init (which surprisingly worked in earlier versions :-).

**Comment by visuallization** [comment]
Great, that was quick! :)
Thanks so much.
