### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by eldinor** [RaananW/babylonjs-webpack-es6#10]
Here is what I get with the fresh clone:
![image](https://user-images.githubusercontent.com/25833327/142739868-a5e634cc-d391-4437-aaa2-2a43e11be824.png)

**Comment by RaananW** [comment]
i'll look into that. seems like a webpack issue (i remember seeing that in other projects as well). It is related to the HTML webpack plugin (though i can't seem to find the reference in the log you pasted).

**Comment by RaananW** [comment]
I couldn't reproduce this, but nonetheless updated the dependencies to make sure they are all compliant with the current version of webpack.
Can you try removing your node modules, reinstalling all npm dependencies and try again?
If it still doesn't work - what os are you using? what node/npm version?

Would be great if you can close it in case it is fixed.

**Comment by eldinor** [comment]
After the latest commit the error has changed:

![image](https://user-images.githubusercontent.com/25833327/143080916-66a1bbbb-fee4-4638-baef-743a71c3ce6e.png)

**Comment by RaananW** [comment]
Something feels off in your configuration. Are you sure this is a clean install?

I just tried with 2 different node versions, cleaned the repo and reinstalled everything and I can't reproduce that.  This is the result of `npm run build:dev` : 

![image](https://user-images.githubusercontent.com/1381702/143089789-ecccfa99-1411-4cec-8519-2f92679277d8.png)

There is a loader for .map files, it is integrated in the repository. I just pushed an upgrade (from 2.02 to 3.0.0), but it was working before already.

**Comment by eldinor** [comment]
I have no problems with this template - https://github.com/BabylonJS/npm-package-template
This one, made according to the documentation, also works fine - https://github.com/eldinor/BabylonTS-NPM-Minimal
Probably you have some module globally installed but not included into package...

**Comment by RaananW** [comment]
> I have no problems with this template - https://github.com/BabylonJS/npm-package-template This one, made according to the documentation, also works fine - https://github.com/eldinor/BabylonTS-NPM-Minimal Probably you have some module globally installed but not included into package...

These are different templates, and this is the first time I see those errors. People are using this, so I assume I would have heard about it more often. I am not saying it's not on my system, I am just saying I can't reproduce this.
And I did ask what system you are using in order to try and reproduce this and got no answer... Would be great to know. It is quite hard to fix something that is not reproducible, where you send images with no stacktrace and no information about the system it is running on.

In general I don't install anything on my global namespace, and avoid doing. If I do need something globally I use npx instead.  The lock file also makes it rather impossible to miss a dependency and its version.

**Comment by eldinor** [comment]
Here is node list:

babylonjs-typescript-webpack-simple-scene@0.0.1 C:\Users\Fiolent2\Source\Repos\babylonjs-webpack-es6
+-- @babylonjs/core@5.0.0-alpha.61
+-- @babylonjs/loaders@5.0.0-alpha.61
+-- @typescript-eslint/eslint-plugin@2.34.0
+-- @typescript-eslint/parser@2.34.0
+-- ammo.js@0.0.2 (git+ssh://git@github.com/kripken/ammo.js.git#43cfc7fb63afc5e5aabddc631f1bb717dcd2725f)
+-- babel-preset-es2015@6.24.1
+-- clean-webpack-plugin@3.0.0
+-- eslint@7.32.0
+-- file-loader@6.2.0
+-- html-webpack-plugin@5.5.0
+-- source-map-loader@2.0.2
+-- ts-loader@8.3.0
+-- typescript@4.5.2
+-- url-loader@4.1.1
+-- webpack-cli@4.9.1
+-- webpack-dev-server@4.5.0
+-- webpack-merge@5.8.0
`-- webpack@5.64.2

**Comment by sebavan** [comment]
And what is your node version, we wonder if it could be this creating the issue.

I will never know how to call you between labris eldinor and Fiolent2 ;-)

**Comment by RaananW** [comment]
Also, can you try updating to the latest version? I updated the source map plugin

**Comment by eldinor** [comment]
Node.js v16.13.0.

I'll do the fresh clone and report.

**Comment by eldinor** [comment]
Fresh clone works! 
Thanks!
(Seems that there were something bad left in the last install besides node_modules even if they would be deleted).
![image](https://user-images.githubusercontent.com/25833327/143100175-d97c7ba1-bdb4-4e67-ac5c-e0fabed62369.png)

**Comment by RaananW** [comment]
I didn't try with 16. Tested on 12 and 14. Might be the issue. I can test tomorrow

**Comment by eldinor** [comment]
Well, it works now :)
