### ISSUE TITLE
Lol, what am I doing wrong?

### ISSUE THREAD

**Issue by unicomp21** [RaananW/babylonjs-webpack-es6#19]
If I try to add thin instances here:
https://github.com/RaananW/babylonjs-webpack-es6/blob/4fa2ea5f214ef09879085a5a96b43e9070c6c3d9/src/scenes/defaultWithTexture.ts#L74

ie
        sphere.position.y = 1;
        const matrix = Matrix.Translation(-2, 2, 0);
        const idx = sphere.thinInstanceAdd(matrix);

Then I get an error:
Uncaught (in promise) TypeError: sphere.thinInstanceAdd is not a function
    at DefaultSceneWithTexture.<anonymous> (defaultWithTexture.ts:76:28)
    at Generator.next (<anonymous>)
    at src_scenes_defaultWithTexture_ts.babylonBundle.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (src_scenes_defaultWithTexture_ts.babylonBundle.js:28:12)
    at DefaultSceneWithTexture.createScene (defaultWithTexture.ts:24:25)
    at index.ts:38:43
    at Generator.next (<anonymous>)
    at fulfilled (createScene.ts:25:3)

**Comment by unicomp21** [comment]
@RaananW ^

**Comment by unicomp21** [comment]
figured it out

**Comment by DiogoNeves** [comment]
> figured it out

Awesome!  
What was the issue? In case anyone else comes across 😀

**Comment by unicomp21** [comment]
@DiogoNeves I simply moved my thininstance creation stuff over here, and it started working.  Perhaps something in the callback stuff is causing deps to get culled in webpack?

https://github.com/RaananW/babylonjs-webpack-es6/blob/master/src/index.ts#L39

**Comment by RaananW** [comment]
This is probably happening because of missing side-effects.

I will find time to add an example for thin instances.
