### ISSUE TITLE
New Feature: Add support for shader imports

### ISSUE THREAD

**Issue by DiogoNeves** [RaananW/babylonjs-webpack-es6#22]
Hi 👋 

Apologies if this is already supported and I missed it!  
Do you think it would be worth adding support for shader code imports?  

I'm happy to do it with some support on getting it with the right structure.  

In my project I:

Created a folder in `src/glsl` for the shaders.  
Currently each effect is a subfolder and includes the vertex and fragment shaders if necessary (e.g. `src/glsl/effect/vertex.glsl`).

Added this to the `webpack.common.js` config:  
```js
{
  test: /\.(glsl|vs|fs)$/,
  loader: 'ts-shader-loader',
  exclude: /node_modules/,
},
```

Still had to add the `glsl.d.ts` file to the `src/glsl` folder, containing:  
```typescript
declare module '*.glsl' {
  const value: string;
  export default value;
}
```

---
Let me know what you think

**Comment by RaananW** [comment]
Oh, no, it isn't supported yet!  Great idea.
Want to submit a PR, or would you rather wait until I have the time to add that?

**Comment by DiogoNeves** [comment]
I can do soonish 😊 are you ok with that folder structure?

the one bit I need help with is coming up with an example if necessary, but I can start without

**Comment by RaananW** [comment]
Sure, i'm fine with the dir structure :-)

**Comment by RaananW** [comment]
I am assigning myself to not forget about it, but feel free to update about progress on your side :-)

**Comment by DiogoNeves** [comment]
FYI I'm starting on this now. It's my first contribution so it may take a little longer than expected 😅

**Comment by DiogoNeves** [comment]
Ok, PR is up @RaananW I tried to provide details, but let me know if you need more information.  
I also understand if you prefer not to merge 😉

**Comment by RaananW** [comment]
Thanks again :-)

**Comment by DiogoNeves** [comment]
I thank you for letting me contribute 😅 glad it was ok
