### ISSUE TITLE
[Feature Request] Test structure

### ISSUE THREAD

**Issue by yuripourre** [RaananW/babylonjs-webpack-es6#23]
This repo saved me a lot of time setting a new project, thank you so much for your efforts.

I think the only step missing to have the *perfect* template repo is the test structure.

I added tests to my private fork but it doesn't look very good, maybe someone with more experience with typescript would be able to come with a proper solution.

**Comment by RaananW** [comment]
Oh, I have a plan to create a visualization test suite for babylon.js projects. I can add it here as well :-)

Might take a while (as always), but this is a wonderful addition.

**Comment by unicomp21** [comment]
What about jest type testing in the browser?  Can we do that too?

**Comment by unicomp21** [comment]
@RaananW grateful for you!  I was hanging by my last neuron, until I found this repo.  Now, life is bliss, lol.

**Comment by RaananW** [comment]
running `npm run test` will now launch playwright validation tests in chrome for the scenes.

Note that if you want the validation tests to be deterministic, make sure you add some event or an observable you can hook into to decide when to take the screenshot.

**Comment by unicomp21** [comment]
I'm not familiar w/ playright, does jest-like tests too?

**Comment by RaananW** [comment]
https://playwright.dev/

**Comment by unicomp21** [comment]
I would be grateful for jest.  I'm working on procedural generation tooling, which is nothing but vector math.  Having both would be awesome.

**Comment by yuripourre** [comment]
@RaananW I don't want you to have more work but I second @unicomp21. I rely on jest tests a lot, I could port my changes to this repo but I changed my fork too much.

**Comment by RaananW** [comment]
All you need is a proper jest configuration if you want to run unit tests in this repo. I'd be more than happy to suggest, however, from experience, a 3D experience is better tested using visual tests and not unit tests.

I'll add the config very soon

**Comment by RaananW** [comment]
A working jest config was added, able to load esm, typescript, and babylon.

**Comment by unicomp21** [comment]
Many thanks @RaananW, appreciate you!

**Comment by yuripourre** [comment]
Thank you @RaananW !!
