### ISSUE TITLE
scene.beginAnimation is not a function (with LoadModelAndEnvScene)

### ISSUE THREAD

**Issue by RamilKadyrov** [RaananW/babylonjs-webpack-es6#42]
Adding 
`import "@babylonjs/core/Animations/animatable"`
to scenes/loadModelAndEnv.ts
fix the error:
Uncaught runtime errors:
ERROR
scene.beginAnimation is not a function
TransitionTo@http://localhost:8080/js/babylonBundle.js:4178:33
_maintainCameraAboveGround@http://localhost:8080/js/babylonBundle.js:8816:95
./node_modules/@babylonjs/core/Behaviors/Cameras/framingBehavior.js/attach/this._onAfterCheckInputsObserver<@http://localhost:8080/js/babylonBundle.js:8641:18
notifyObservers@http://localhost:8080/js/babylonBundle.js:99182:49
_checkInputs@http://localhost:8080/js/babylonBundle.js:15652:43
_checkInputs@http://localhost:8080/js/babylonBundle.js:17520:15
_checkInputs@http://localhost:8080/js/babylonBundle.js:14730:15
update@http://localhost:8080/js/babylonBundle.js:15640:14
render@http://localhost:8080/js/babylonBundle.js:121575:35
./src/index.ts/babylonInit/<@http://localhost:8080/js/babylonBundle.js:3541:15
_renderFrame@http://localhost:8080/js/babylonBundle.js:32496:13
_renderLoop@http://localhost:8080/js/babylonBundle.js:32523:26
./node_modules/@babylonjs/core/Engines/thinEngine.js/runRenderLoop/this._boundRenderFunction@http://localhost:8080/js/babylonBundle.js:35252:52

**Comment by RaananW** [comment]
This is probably code that you added, since the code in the repo doesn't call beginAnimation

This is the right solution, but it is a part of your code and is not needed in the template itself. If imissed something, please let me know! otherwise I am closing it for now

**Comment by RamilKadyrov** [comment]
I did not added anything about animation. I just changed default scene to the LoadModelAndEnv.

The issue is in the file loadModelAndEnvScene.ts line 46
 
`camera.useFramingBehavior = true;`

In the result it calls _maintainCameraAboveGround that contains animation.

**Comment by RaananW** [comment]
i'll check it again then! 
Thanks for answering :-)

**Comment by RamilKadyrov** [comment]
I had to add steps to reproduce in the first message. :-)
1. Change the DefaultSceneWithTexture in createScene.ts to LoadModelAndEnvScene
2. npm start
3. in a browser manually move the camera under the ground. 
4. after couple of seconds the camera automatically tries to move above the ground because of useFramingBehavior, but the animation module is not imported and as a result the error message showed.

**Comment by RaananW** [comment]
Done, thanks a lot.
